#ifndef LANG_HPP_BB6D2D7F_CD59_4D0F_B11D_2077A8A22947
#define LANG_HPP_BB6D2D7F_CD59_4D0F_B11D_2077A8A22947
#pragma once

/*
lang.hpp
*/
/*
Copyright © 2010 Far Group
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. The name of the authors may not be used to endorse or promote products
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

// Internal:

// Platform:

// Common:

// External:

//----------------------------------------------------------------------------

// Note: https://www.microsoft.com/language is a good source of system- and UI-specific translations.

enum class lng:int
{
	MYes,
	MNo,
	MOk,

	MHYes,
	MHNo,
	MHOk,

	MCancel,
	MReset,
	MRetry,
	MSkip,
	MAbort,
	MIgnore,
	MDelete,

	MHCancel,
	MHRetry,
	MHSkip,
	MHSkipAll,
	MHAbort,
	MHIgnore,
	MHDelete,
	MHRemove,
	MHSplit,

	MWarning,
	MError,

	MQuit,
	MAskQuit,

	// Panels: functional keys
	MF1,
	MF2,
	MF3,
	MF4,
	MF5,
	MF6,
	MF7,
	MF8,
	MF9,
	MF10,
	MF11,
	MF12,

	MShiftF1,
	MShiftF2,
	MShiftF3,
	MShiftF4,
	MShiftF5,
	MShiftF6,
	MShiftF7,
	MShiftF8,
	MShiftF9,
	MShiftF10,
	MShiftF11,
	MShiftF12,

	MAltF1,
	MAltF2,
	MAltF3,
	MAltF4,
	MAltF5,
	MAltF6,
	MAltF7,
	MAltF8,
	MAltF9,
	MAltF10,
	MAltF11,
	MAltF12,

	MCtrlF1,
	MCtrlF2,
	MCtrlF3,
	MCtrlF4,
	MCtrlF5,
	MCtrlF6,
	MCtrlF7,
	MCtrlF8,
	MCtrlF9,
	MCtrlF10,
	MCtrlF11,
	MCtrlF12,

	// Main AltShift
	MAltShiftF1,
	MAltShiftF2,
	MAltShiftF3,
	MAltShiftF4,
	MAltShiftF5,
	MAltShiftF6,
	MAltShiftF7,
	MAltShiftF8,
	MAltShiftF9,
	MAltShiftF10,
	MAltShiftF11,
	MAltShiftF12,

	// Main CtrlShift
	MCtrlShiftF1,
	MCtrlShiftF2,
	MCtrlShiftF3,
	MCtrlShiftF4,
	MCtrlShiftF5,
	MCtrlShiftF6,
	MCtrlShiftF7,
	MCtrlShiftF8,
	MCtrlShiftF9,
	MCtrlShiftF10,
	MCtrlShiftF11,
	MCtrlShiftF12,

	// Main CtrlAlt
	MCtrlAltF1,
	MCtrlAltF2,
	MCtrlAltF3,
	MCtrlAltF4,
	MCtrlAltF5,
	MCtrlAltF6,
	MCtrlAltF7,
	MCtrlAltF8,
	MCtrlAltF9,
	MCtrlAltF10,
	MCtrlAltF11,
	MCtrlAltF12,

	// Main CtrlAltShift
	MCtrlAltShiftF1,
	MCtrlAltShiftF2,
	MCtrlAltShiftF3,
	MCtrlAltShiftF4,
	MCtrlAltShiftF5,
	MCtrlAltShiftF6,
	MCtrlAltShiftF7,
	MCtrlAltShiftF8,
	MCtrlAltShiftF9,
	MCtrlAltShiftF10,
	MCtrlAltShiftF11,
	// Panels: end of functional keys
	MCtrlAltShiftF12,

	MHistoryTitle,
	MHistoryInfoTitle,
	MHistoryInfoFolder,
	MFolderHistoryTitle,
	MViewHistoryTitle,
	MViewHistoryIsCreate,
	MHistoryView,
	MHistoryEdit,
	MHistoryExt,

	MHistoryClear,
	MClear,

	MConfigSystemTitle,
	MConfigRecycleBin,
	MConfigSystemCopy,
	MConfigCopySharing,
	MConfigScanJunction,
	MConfigSmartFolderMonitor,
	MConfigSaveHistory,
	MConfigSaveFoldersHistory,
	MConfigSaveViewHistory,
	MConfigRegisteredTypes,
	MConfigUpdateEnvironment,
	MConfigElevation,
	MConfigElevationModify,
	MConfigElevationRead,
	MConfigElevationUsePrivileges,
	MConfigSortingCollation,
	MConfigSortingOrdinal,
	MConfigSortingInvariant,
	MConfigSortingLinguistic,
	MConfigSortingDigitsAsNumbers,
	MConfigSortingCase,
	MConfigAutoSave,

	MConfigTreeTitle,
	MConfigTreeAutoChange,
	MConfigTreeLabelMinFolder,
	MConfigTreeLabel1,
	MConfigTreeLabelLocalDisk,
	MConfigTreeLabelNetDisk,
	MConfigTreeLabelNetPath,
	MConfigTreeLabelRemovableDisk,
	MConfigTreeLabelCDDisk,
	MConfigTreeLabelExceptPath,
	MConfigTreeLabelSaveLocalPath,
	MConfigTreeLabelSaveNetPath,

	MConfigPanelTitle,
	MConfigHidden,
	MConfigHighlight,
	MConfigSelectFolders,
	MConfigRightClickSelect,
	MConfigSortFolderExt,
	MConfigAllowReverseSort,
	MConfigAutoUpdateLimit,
	MConfigAutoUpdateLimit2,
	MConfigAutoUpdateRemoteDrive,
	MConfigShowColumns,
	MConfigShowStatus,
	MConfigDetailedJunction,
	MConfigShowTotal,
	MConfigShowFree,
	MConfigShowScrollbar,
	MConfigShowScreensNumber,
	MConfigShowSortMode,
	MConfigShowDotsInRoot,

	MConfigInterfaceTitle,
	MConfigClock,
	MConfigMouse,
	MConfigKeyBar,
	MConfigMenuBar,
	MConfigSaver,
	MConfigSaverMinutes,
	MConfigCopyTotal,
	MConfigCopyTimeRule,
	MConfigDeleteTotal,
	MConfigPgUpChangeDisk,
	MConfigUseVirtualTerminalForRendering,
	MConfigFullWidthAwareRendering,
	MConfigClearType,
	MConfigSetConsoleIcon,
	MConfigSetAdminConsoleIcon,
	MConfigTitleAddons,

	MConfigDlgSetsTitle,
	MConfigDialogsEditHistory,
	MConfigDialogsEditBlock,
	MConfigDialogsDelRemovesBlocks,
	MConfigDialogsAutoComplete,
	MConfigDialogsEULBsClear,
	MConfigDialogsMouseButton,

	MConfigVMenuTitle,
	MConfigVMenuLBtnClick,
	MConfigVMenuRBtnClick,
	MConfigVMenuMBtnClick,
	MConfigVMenuClickCancel,
	MConfigVMenuClickApply,
	MConfigVMenuClickIgnore,

	MConfigCmdlineTitle,
	MConfigCmdlineEditBlock,
	MConfigCmdlineDelRemovesBlocks,
	MConfigCmdlineAutoComplete,
	MConfigCmdlineUsePromptFormat,
	MConfigCmdlineUseHomeDir,
	MConfigCmdlinePromptFormatAdmin,

	MConfigAutoCompleteTitle,

	MConfigAutoCompleteShowList,

	MConfigAutoCompleteModalList,

	MConfigAutoCompleteAutoAppend,

	MConfigInfoPanelTitle,
	MConfigInfoPanelCNTitle,
	MConfigInfoPanelCNPhysicalNetBIOS,
	MConfigInfoPanelCNPhysicalDnsHostname,
	MConfigInfoPanelCNPhysicalDnsDomain,
	MConfigInfoPanelCNPhysicalDnsFullyQualified,
	MConfigInfoPanelCNNetBIOS,
	MConfigInfoPanelCNDnsHostname,
	MConfigInfoPanelCNDnsDomain,
	MConfigInfoPanelCNDnsFullyQualified,
	MConfigInfoPanelUNTitle,
	MConfigInfoPanelUNLogon,
	MConfigInfoPanelUNFullyQualifiedDN,
	MConfigInfoPanelUNSamCompatible,
	MConfigInfoPanelUNDisplay,
	MConfigInfoPanelUNUniqueId,
	MConfigInfoPanelUNCanonical,
	MConfigInfoPanelUNUserPrincipal,
	MConfigInfoPanelUNServicePrincipal,
	MConfigInfoPanelUNDnsDomain,
	MConfigInfoPanelUNGivenName,
	MConfigInfoPanelUNSurname,
	MConfigInfoPanelShowPowerStatus,
	MConfigInfoPanelShowCDInfo,

	MMenuInfoShowModeTitle,
	MMenuInfoShowModeDisk,
	MMenuInfoShowModeMemory,
	MMenuInfoShowModeDirDiz,
	MMenuInfoShowModePluginDiz,
	MMenuInfoShowModePower,

	MViewConfigTitle,
	MViewConfigExternalF3,
	MViewConfigExternalCommand,
	MViewConfigInternal,
	MViewConfigSavePos,
	MViewConfigSaveShortPos,
	MViewConfigSaveCodepage,
	MViewConfigSaveWrapMode,
	MViewConfigSaveViewMode,
	MViewConfigDetectDumpMode,
	MViewAutoDetectCodePage,
	MViewConfigTabSize,
	MViewConfigScrollbar,
	MViewConfigArrows,
	MViewConfigPersistentSelection,
	MViewConfigDefaultCodePage,
	MViewConfigMaxLineSize,
	MViewConfigVisible0x00,

	MEditConfigTitle,
	MEditConfigEditorF4,
	MEditConfigEditorCommand,
	MEditConfigInternal,
	MEditConfigExpandTabsTitle,

	MEditConfigDoNotExpandTabs,
	MEditConfigExpandTabs,
	MEditConfigConvertAllTabsToSpaces,
	MEditConfigPersistentBlocks,

	MEditConfigDelRemovesBlocks,
	MEditConfigAutoIndent,
	MEditConfigSavePos,
	MEditConfigSaveShortPos,
	MEditCursorBeyondEnd,
	MEditAutoDetectCodePage,
	MEditShareWrite,
	MEditLockROFileModification,
	MEditWarningBeforeOpenROFile,
	MEditConfigTabSize,
	MEditConfigScrollbar,
	MEditShowWhiteSpace,
	MEditConfigSelFound,
	MEditConfigCursorAtEnd,
	MEditConfigDefaultCodePage,
	MConfigEditor,

	MSaveSetupTitle,
	MSaveSetupAsk1,
	MSaveSetupAsk2,
	MSaveSetup,

	MCopyDlgTitle,
	MMoveDlgTitle,
	MLinkDlgTitle,
	MCopySecurity,
	MCopySecurityDefault,
	MCopySecurityCopy,
	MCopySecurityInherit,
	MCopyIfFileExist,
	MCopyAsk,
	MCopyAskRO,
	MCopyOnlyNewerFiles,
	MLinkType,
	MLinkTypeJunction,
	MLinkTypeHardlink,
	MLinkTypeSymlink,
	MLinkTypeSymlinkFile,
	MLinkTypeSymlinkDirectory,
	MCopyPreserveAllTimestamps,
	MCopySymLinkContents,
	MCopyMultiActions,
	MCopyDlgCopy,
	MCopyDlgTree,
	MCopyDlgCancel,
	MCopyDlgRename,
	MCopyDlgLink,
	MCopyDlgTotal,
	MCopyPrepareSecury,
	MCopyUseFilter,
	MCopySetFilter,

	MCopyFile,
	MMoveFile,
	MLinkFile,
	MCopyFiles,
	MMoveFiles,
	MLinkFiles,
	MCMLTargetTO,
	MCMLTargetIN,
	MCMLItems0,
	MCMLItemsA,
	MCMLItemsS,

	MCopyIncorrectTargetList,

	MCopyCopyingTitle,
	MCopyMovingTitle,

	MCopyCannotFind,

	MCannotCopyFolderToItself1,
	MCannotCopyFolderToItself2,

	MCopyCannotCreateFolder,
	MCopyCannotRenameFolder,
	MCopyIgnore,
	MCopyIgnoreAll,
	MCopyRetry,
	MCopySkip,
	MCopySkipAll,
	MCopyCancel,
	MCopyDecrypt,
	MCopyDecryptAll,

	MCopyCannotCreateLink,
	MCopyFolderNotEmpty,
	MCopyCannotCreateJunctionToFile,

	MCopyCannotCreateVolMount,
	MCopyMountVolFailed,
	MCopyMountVolFailed2,
	MCopyMountName,

	MCannotCopyFileToItself1,
	MCannotCopyFileToItself2,

	MCopyStream1,
	MCopyStream2,
	MCopyStream3,
	MCopyStream4,

	MCopyDirectoryOrFile,
	MCopyDirectoryOrFileDirectory,
	MCopyDirectoryOrFileFile,

	MCopyFileExist,
	MCopySource,
	MCopyDest,
	MCopyOverwrite,
	MCopyAppend,
	MCopyRename,
	MCopyRememberChoice,
	MCopyRenameTitle,
	MCopyRenameText,

	MCopyFileRO,
	MCopyAskDelete,
	MCopyDeleteRO,
	MCopyDeleteAllRO,

	MCannotCopy,
	MCannotMove,
	MCannotLink,
	MCannotCopyTo,
	MCopyEncryptWarn1,
	MCopyEncryptWarn2,

	MCopyReadError,
	MCopyWriteError,
	MCopyCannotReserveSpace,

	MCopyFilesTotalInfo,
	MCopyBytesTotalInfo,
	MCopyMoving,
	MCopyCopying,
	MCopyTo,

	MDeleteTitle,
	MAskDelete,
	MAskDeleteRecycle,
	MDeleteWipeTitle,
	MAskWipe,
	MAskDeleteFolder,
	MAskDeleteFile,
	MAskDeleteObjects,
	MAskDeleteLink,
	MAskDeleteAndMore,

	MDeleteFolderTitle,
	MWipeFolderTitle,
	MDeleteFilesTitle,
	MWipeFilesTitle,
	MDeleteFolderConfirm,
	MWipeFolderConfirm,
	MRecycleFolderConfirm,
	MRecycleFolderConfirmDeleteLink1,
	MRecycleFolderConfirmDeleteLink2,
	MRecycleFolderConfirmDeleteLink3,
	MRecycleFolderConfirmDeleteLink4,
	MDeleteWipe,
	MDeleteRecycle,
	MDeleteFileDelete,
	MDeleteFileWipe,
	MDeleteFileAll,
	MDeleteFileSkip,
	MDeleteFileSkipAll,
	MDeleteFileCancel,

	MDeletingTitle,

	MDeleting,
	MDeletingWiping,

	MDeleteRO,
	MAskDeleteRO,
	MAskWipeRO,

	MDeleteHardLink1,
	MDeleteHardLink2,
	MDeleteHardLink3,

	MCannotDeleteFile,
	MCannotDeleteFolder,
	MDeleteRetry,
	MDeleteSkip,
	MDeleteSkipAll,
	MDeleteCancel,
	MCannotRecycleFile,
	MCannotRecycleFolder,
	MTryToDeletePermanently,

	MCannotGetSecurity,
	MCannotSetSecurity,

	MSearchReplaceSearchTitle,

	MSearchReplaceReplaceTitle,
	MSearchReplaceText,
	MSearchReplaceHex,
	MSearchReplacePickWord,
	MSearchReplacePickSelection,
	MSearchReplaceSearchFor,
	MSearchReplaceReplaceWith,
	MSearchReplaceCase,
	MSearchReplaceWholeWords,
	MSearchReplaceFuzzy,
	MSearchReplaceRegexp,
	MSearchReplacePreserveStyle,
	MSearchReplaceFind,
	MSearchReplaceFindNext,
	MSearchReplaceFindPrev,
	MSearchReplaceReplace,
	MSearchReplaceReplaceNext,
	MSearchReplaceReplacePrev,
	MSearchReplaceAll,
	MSearchReplaceCancel,

	MEditTitle,
	MAskReload,
	MCurrent,
	MReload,
	MNewOpen,
	MEditCannotOpen,
	MEditReading,
	MEditAskSave,
	MEditAskSaveExt,
	MEditBtnSaveAs,

	MEditRO,
	MEditExists,
	MEditOvr,
	MEditSaving,
	// Up to 3 characters
	MEditStatusLine,
	// Up to 3 characters
	MEditStatusCol,
	// Up to 2 characters
	MEditStatusChar,

	MEditRSH,
	MEditFileGetSizeError,
	MEditFileLong,
	MEditFileLong2,
	MEditROOpen,

	MEditCanNotEditDirectory,

	MEditSearchingFor,
	MEditSearchStatistics,
	MEditNotFound,

	MEditAskReplace,
	MEditAskReplaceWith,
	MEditReplace,
	MEditReplaceAll,
	MEditSkip,
	MEditCancel,
	MEditOpenCreateLabel,
	MEditOpenAutoDetect,
	MDefaultCP,

	MGoTo,
	MGoToHex,

	MFolderShortcutsTitle,
	MShortcutNone,
	MShortcutPlugin,
	MFSShortcutName,
	MFSShortcutPath,
	MFSShortcutPluginFile,
	MFSShortcutPluginData,
	MNeedNearPath,
	MSaveThisShortcut,

	// Editor: functional keys
	MEditF1,
	MEditF2,
	MEditF3,
	MEditF4,
	MEditF5,
	MEditF6,
	MEditF7,
	MEditF8,
	MEditF9,
	MEditF10,
	MEditF11,
	MEditF12,

	// Editor: Shift
	MEditShiftF1,
	MEditShiftF2,
	MEditShiftF3,
	MEditShiftF4,
	MEditShiftF5,
	MEditShiftF6,
	MEditShiftF7,
	MEditShiftF8,
	MEditShiftF9,
	MEditShiftF10,
	MEditShiftF11,
	MEditShiftF12,

	// Editor: Alt
	MEditAltF1,
	MEditAltF2,
	MEditAltF3,
	MEditAltF4,
	MEditAltF5,
	MEditAltF6,
	MEditAltF7,
	MEditAltF8,
	MEditAltF9,
	MEditAltF10,
	MEditAltF11,
	MEditAltF12,

	// Editor: Ctrl
	MEditCtrlF1,
	MEditCtrlF2,
	MEditCtrlF3,
	MEditCtrlF4,
	MEditCtrlF5,
	MEditCtrlF6,
	MEditCtrlF7,
	MEditCtrlF8,
	MEditCtrlF9,
	MEditCtrlF10,
	MEditCtrlF11,
	MEditCtrlF12,

	// Editor: AltShift
	MEditAltShiftF1,
	MEditAltShiftF2,
	MEditAltShiftF3,
	MEditAltShiftF4,
	MEditAltShiftF5,
	MEditAltShiftF6,
	MEditAltShiftF7,
	MEditAltShiftF8,
	MEditAltShiftF9,
	MEditAltShiftF10,
	MEditAltShiftF11,
	MEditAltShiftF12,

	// Editor: CtrlShift
	MEditCtrlShiftF1,
	MEditCtrlShiftF2,
	MEditCtrlShiftF3,
	MEditCtrlShiftF4,
	MEditCtrlShiftF5,
	MEditCtrlShiftF6,
	MEditCtrlShiftF7,
	MEditCtrlShiftF8,
	MEditCtrlShiftF9,
	MEditCtrlShiftF10,
	MEditCtrlShiftF11,
	MEditCtrlShiftF12,

	// Editor: CtrlAlt
	MEditCtrlAltF1,
	MEditCtrlAltF2,
	MEditCtrlAltF3,
	MEditCtrlAltF4,
	MEditCtrlAltF5,
	MEditCtrlAltF6,
	MEditCtrlAltF7,
	MEditCtrlAltF8,
	MEditCtrlAltF9,
	MEditCtrlAltF10,
	MEditCtrlAltF11,
	MEditCtrlAltF12,

	// Editor: CtrlAltShift
	MEditCtrlAltShiftF1,
	MEditCtrlAltShiftF2,
	MEditCtrlAltShiftF3,
	MEditCtrlAltShiftF4,
	MEditCtrlAltShiftF5,
	MEditCtrlAltShiftF6,
	MEditCtrlAltShiftF7,
	MEditCtrlAltShiftF8,
	MEditCtrlAltShiftF9,
	MEditCtrlAltShiftF10,
	MEditCtrlAltShiftF11,
	MEditCtrlAltShiftF12,
	// Editor: end of functional keys
	// This is another text for F8
	MEditF8DOS,

	MEditSaveAs,
	MEditCodePage,
	MEditAddSignature,
	MEditSaveAsFormatTitle,
	MEditSaveOriginal,
	MEditSaveDOS,
	MEditSaveUnix,
	MEditSaveMac,
	MEditCannotSave,
	MEditSavedChangedNonFile,
	MEditSavedChangedNonFile1,
	MEditSavedChangedNonFile2,
	MEditNewPath1,
	MEditNewPath2,
	MEditNewPath3,
	MEditNewPlugin1,
	MEditorLoadCPWarn1,
	MEditorLoadCPWarn2,
	MEditorReloadCPWarnLost1,
	MEditorReloadCPWarnLost2,
	MEditorSwitchCPConfirm,
	MEditDataLostWarn,
	MEditorSaveNotRecommended,
	MEditorSave,
	MEditorSaveCPWarnShow,
	MEditorCPNotSupported,

	MColumnName,
	MColumnExtension,
	MColumnSize,
	MColumnAlocatedSize,
	MColumnDate,
	MColumnTime,
	MColumnWrited,
	MColumnCreated,
	MColumnAccessed,
	MColumnChanged,
	MColumnAttr,
	MColumnDescription,
	MColumnOwner,
	MColumnMumLinks,
	MColumnNumStreams,
	MColumnStreamsSize,
	MColumnUnknown,

	MListUp,
	MListFolder,
	MListSymlink,
	MListJunction,
	MListVolMount,
	MListUnknownReparsePoint,
	MListBrackets,
	MListBytes,
	MListKb,
	MListMb,
	MListGb,
	MListTb,
	MListPb,
	MListEb,
	// {3} replacement field can receive a sum of files & folders
	MListFileSize,
	MListFileSizeStatus,
	MListFreeSize,

	MDirInfoViewTitle,
	MFileToEdit,

	MUnselectTitle,
	MSelectTitle,
	MSelectFilter,

	MCompareTitle,
	MCompareFilePanelsRequired1,
	MCompareFilePanelsRequired2,
	MCompareSameFolders1,
	MCompareSameFolders2,

	MSelectAssocTitle,

	MAssocTitle,
	MAskDelAssoc,

	MFileAssocTitle,
	MFileAssocMasks,
	MFileAssocDescr,
	MFileAssocExec,
	MFileAssocAltExec,
	MFileAssocView,
	MFileAssocAltView,
	MFileAssocEdit,
	MFileAssocAltEdit,

	// Viewer: functional keys
	MViewF1,
	MViewF2,
	MViewF3,
	MViewF4,
	MViewF5,
	MViewF6,
	MViewF7,
	MViewF8,
	MViewF9,
	MViewF10,
	MViewF11,
	MViewF12,

	// Viewer: Shift
	MViewShiftF1,
	MViewShiftF2,
	MViewShiftF3,
	MViewShiftF4,
	MViewShiftF5,
	MViewShiftF6,
	MViewShiftF7,
	MViewShiftF8,
	MViewShiftF9,
	MViewShiftF10,
	MViewShiftF11,
	MViewShiftF12,

	// Viewer: Alt
	MViewAltF1,
	MViewAltF2,
	MViewAltF3,
	MViewAltF4,
	MViewAltF5,
	MViewAltF6,
	MViewAltF7,
	MViewAltF8,
	MViewAltF9,
	MViewAltF10,
	MViewAltF11,
	MViewAltF12,

	// Viewer: Ctrl
	MViewCtrlF1,
	MViewCtrlF2,
	MViewCtrlF3,
	MViewCtrlF4,
	MViewCtrlF5,
	MViewCtrlF6,
	MViewCtrlF7,
	MViewCtrlF8,
	MViewCtrlF9,
	MViewCtrlF10,
	MViewCtrlF11,
	MViewCtrlF12,

	// Viewer: AltShift
	MViewAltShiftF1,
	MViewAltShiftF2,
	MViewAltShiftF3,
	MViewAltShiftF4,
	MViewAltShiftF5,
	MViewAltShiftF6,
	MViewAltShiftF7,
	MViewAltShiftF8,
	MViewAltShiftF9,
	MViewAltShiftF10,
	MViewAltShiftF11,
	MViewAltShiftF12,

	// Viewer: CtrlShift
	MViewCtrlShiftF1,
	MViewCtrlShiftF2,
	MViewCtrlShiftF3,
	MViewCtrlShiftF4,
	MViewCtrlShiftF5,
	MViewCtrlShiftF6,
	MViewCtrlShiftF7,
	MViewCtrlShiftF8,
	MViewCtrlShiftF9,
	MViewCtrlShiftF10,
	MViewCtrlShiftF11,
	MViewCtrlShiftF12,

	// Viewer: CtrlAlt
	MViewCtrlAltF1,
	MViewCtrlAltF2,
	MViewCtrlAltF3,
	MViewCtrlAltF4,
	MViewCtrlAltF5,
	MViewCtrlAltF6,
	MViewCtrlAltF7,
	MViewCtrlAltF8,
	MViewCtrlAltF9,
	MViewCtrlAltF10,
	MViewCtrlAltF11,
	MViewCtrlAltF12,

	// Viewer: CtrlAltShift
	MViewCtrlAltShiftF1,
	MViewCtrlAltShiftF2,
	MViewCtrlAltShiftF3,
	MViewCtrlAltShiftF4,
	MViewCtrlAltShiftF5,
	MViewCtrlAltShiftF6,
	MViewCtrlAltShiftF7,
	MViewCtrlAltShiftF8,
	MViewCtrlAltShiftF9,
	MViewCtrlAltShiftF10,
	MViewCtrlAltShiftF11,
	MViewCtrlAltShiftF12,
	MViewF2Unwrap,
	// this is another text for F4
	MViewF4Text,
	// this is another text for F4
	MViewF4Dump,
	// Viewer: end of functional keys
	// This is another text for F8
	MViewF8DOS,
	MViewMode,
	MInViewer,
	MInEditor,

	MFilterTitle,
	MPanelFileType,
	MFolderFileType,
	MCanEditCustomFilterOnly,
	MAskDeleteFilter,
	MCanDeleteCustomFilterOnly,

	MFindFileTitle,
	MFindFileMasks,
	MFindFileContaining,
	MFindFileText,
	MFindFileHex,
	MFindFileCodePage,
	MFindFileAllCodePages,
	MFindFileSelectedCodePages,
	MFindFileCase,
	MFindFileWholeWords,
	MFindFileFuzzy,
	MFindFileNotContaining,
	MFindFileArchives,
	MFindFileFolders,
	MFindFileSymLinks,
	MFindFileAlternateStreams,
	MFindFileSearchArea,
	MFindFileSearchAllDisks,
	MFindFileSearchAllButNetwork,
	MFindFileSearchInPATH,
	MFindFileSearchFromRootOfDrive,
	MFindFileSearchFromRootFolder,
	MFindFileSearchFromCurrent,
	MFindFileSearchInCurrent,
	MFindFileSearchInSelected,
	MFindFileUseFilter,
	MFindFileUsingFilter,
	MFindFileFind,
	MFindFileDrive,
	MFindFileSetFilter,
	MFindFileAdvanced,
	MFindFileSearchingIn,
	MFindFileNewSearch,
	MFindFileGoTo,
	MFindFileView,
	MFindFilePanel,
	MFindFileStop,

	MFindFileDone,
	MFindFileCancel,

	MFindFileFound,

	MFindFileAdvancedTitle,
	MFindFileSearchFirst,
	MFindFileSearchOutputFormat,
	MFindAlternateModeTypes,
	MFindAlternateModeWidths,

	MFoldTreeSearch,

	MGetCodePageTitle,
	MGetCodePageSystem,
	MGetCodePageUnicode,
	MGetCodePageFavorites,
	MGetCodePageOther,
	MGetCodePageEditCodePageName,
	MGetCodePageResetCodePageName,

	MHighlightTitle,
	MHighlightUpperSortGroup,
	MHighlightLowerSortGroup,
	MHighlightLastGroup,
	MHighlightAskDel,
	MHighlightWarning,
	MHighlightAskRestore,

	MHighlightEditTitle,
	MHighlightMark,
	MHighlightInheritMark,
	MHighlightColors,
	MHighlightFileName1,
	MHighlightFileName2,
	MHighlightFileName3,
	MHighlightFileName4,
	MHighlightMarking1,
	MHighlightMarking2,
	MHighlightMarking3,
	MHighlightMarking4,
	MHighlightExample,
	MHighlightContinueProcessing,

	MInfoTitle,
	MInfoCompName,
	MInfoCompDescription,
	MInfoUserName,
	MInfoUserDescription,
	MInfoUserAccessLevel,
	MInfoUserAccessLevelGuest,
	MInfoUserAccessLevelUser,
	MInfoUserAccessLevelAdministrator,
	MInfoUserAccessLevelUnknown,
	MInfoDiskTitle,
	MInfoRemovable,
	MInfoFixed,
	MInfoNetwork,
	MInfoCDROM,
	MInfoCDR,
	MInfoCDRW,
	MInfoCDRWDVD,
	MInfoDVDROM,
	MInfoDVDR,
	MInfoDVDRW,
	MInfoDVDRAM,
	MInfoBDROM,
	MInfoBDR,
	MInfoBDRE,
	MInfoHDDVDROM,
	MInfoHDDVDR,
	MInfoHDDVDRW,
	MInfoHDDVDRAM,
	MInfoRAM,
	MInfoSUBST,
	MInfoVirtual,
	MInfoUnknown,
	MInfoMetricTotal,
	MInfoMetricAvailable,
	MInfoDisk,
	MInfoDiskSpace,
	MInfoDiskLabel,
	MInfoDiskNumber,
	MInfoMemory,
	MInfoMemoryCommittable,
	MInfoMemoryAddressable,
	MInfoMemoryPhysical,
	MInfoMetricMemoryInstalled,
	MInfoDescription,
	MInfoDizAbsent,
	MInfoPlugin,
	MInfoPowerStatus,
	MInfoPowerStatusAC,
	MInfoPowerStatusACOffline,
	MInfoPowerStatusACOnline,
	MInfoPowerStatusACBackUp,
	MInfoPowerStatusACUnknown,
	MInfoPowerStatusBCLifePercent,
	MInfoPowerStatusBCLifePercentUnknown,
	MInfoPowerStatusBC,
	MInfoPowerStatusBCHigh,
	MInfoPowerStatusBCLow,
	MInfoPowerStatusBCCritical,
	MInfoPowerStatusBCCharging,
	MInfoPowerStatusBCNoSysBat,
	MInfoPowerStatusBCUnknown,
	MInfoPowerStatusBCTimeRem,
	MInfoPowerStatusBCFullTimeRem,
	MInfoPowerStatusUnknown,
	MAccessDenied,

	MCannotExecute,
	MCannotInvokeComspec,
	MCheckComspecVar,
	MScanningFolder,

	MMakeFolderTitle,
	MCreateFolder,
	MMakeFolderLinkType,
	MMakeFolderLinkNone,
	MMakeFolderLinkJunction,
	MMakeFolderLinkSymlink,
	MMakeFolderLinkTarget,
	MMultiMakeDir,
	MIncorrectDirList,
	MCannotCreateFolder,

	MMenuBriefView,
	MMenuMediumView,
	MMenuFullView,
	MMenuWideView,
	MMenuDetailedView,
	MMenuDizView,
	MMenuLongDizView,
	MMenuOwnersView,
	MMenuLinksView,
	MMenuAlternativeView,

	MMenuInfoPanel,
	MMenuTreePanel,
	MMenuQuickView,
	MMenuSortModes,
	MMenuLongNames,
	MMenuTogglePanel,
	MMenuReread,
	MMenuChangeDrive,

	MMenuView,
	MMenuEdit,
	MMenuCopy,
	MMenuMove,
	MMenuLink,
	MMenuCreateFolder,
	MMenuDelete,
	MMenuWipe,
	MMenuAdd,
	MMenuExtract,
	MMenuArchiveCommands,
	MMenuAttributes,
	MMenuApplyCommand,
	MMenuDescribe,
	MMenuSelectGroup,
	MMenuUnselectGroup,
	MMenuInvertSelection,
	MMenuRestoreSelection,

	MMenuFindFile,
	MMenuHistory,
	MMenuVideoMode,
	MMenuFindFolder,
	MMenuViewHistory,
	MMenuFoldersHistory,
	MMenuSwapPanels,
	MMenuTogglePanels,
	MMenuCompareFolders,
	MMenuUserMenu,
	MMenuFileAssociations,
	MMenuFolderShortcuts,
	MMenuFilter,
	MMenuPluginCommands,
	MMenuWindowsList,
	MMenuProcessList,
	MMenuHotPlugList,

	MMenuSystemSettings,
	MMenuPanelSettings,
	MMenuTreeSettings,
	MMenuInterface,
	MMenuLanguages,
	MMenuPluginsConfig,
	MMenuPluginsManagerSettings,
	MMenuDialogSettings,
	MMenuVMenuSettings,
	MMenuCmdlineSettings,
	MMenuAutoCompleteSettings,
	MMenuInfoPanelSettings,
	MMenuMaskGroups,
	MMenuConfirmation,
	MMenuFilePanelModes,
	MMenuFileDescriptions,
	MMenuFolderInfoFiles,
	MMenuViewer,
	MMenuEditor,
	MMenuCodePages,
	MMenuColors,
	MMenuFilesHighlighting,
	MMenuSaveSetup,
	MMenuTogglePanelRight,
	MMenuChangeDriveRight,

	MMenuLeftTitle,
	MMenuFilesTitle,
	MMenuCommandsTitle,
	MMenuOptionsTitle,
	MMenuRightTitle,

	MMenuSortTitle,
	MMenuSortByName,
	MMenuSortByExt,
	MMenuSortByWrite,
	MMenuSortBySize,
	MMenuUnsorted,
	MMenuSortByCreation,
	MMenuSortByAccess,
	MMenuSortByChange,
	MMenuSortByDiz,
	MMenuSortByOwner,
	MMenuSortByAllocatedSize,
	MMenuSortByNumLinks,
	MMenuSortByNumStreams,
	MMenuSortByStreamsSize,
	MMenuSortByNameOnly,
	MMenuSortUseGroups,
	MMenuSortSelectedFirst,
	MMenuSortDirectoriesFirst,
	MMaskGroupTitle,
	MMaskGroupName,
	MMaskGroupMasks,
	MMaskGroupAskDelete,
	MMaskGroupRestore,
	MMaskGroupFindMask,
	MMaskGroupTotal,

	MChangeDriveTitle,
	MChangeDriveRemovable,
	MChangeDriveFixed,
	MChangeDriveNetwork,
	MChangeDriveDisconnectedNetwork,
	MChangeDriveCDROM,
	MChangeDriveCDR,
	MChangeDriveCDRW,
	MChangeDriveCDRWDVD,
	MChangeDriveDVDROM,
	MChangeDriveDVDR,
	MChangeDriveDVDRW,
	MChangeDriveDVDRAM,
	MChangeDriveBDROM,
	MChangeDriveBDR,
	MChangeDriveBDRE,
	MChangeDriveHDDVDROM,
	MChangeDriveHDDVDR,
	MChangeDriveHDDVDRW,
	MChangeDriveHDDVDRAM,
	MChangeDriveRAM,
	MChangeDriveSUBST,
	MChangeDriveVirtual,
	MChangeDriveLabelAbsent,
	MChangeDriveCannotReadDisk,
	MChangeDriveCannotDisconnect,
	MChangeDriveCannotDelSubst,
	MChangeDriveCannotDetach,
	MChangeDriveOpenFiles,

	MChangeSUBSTDisconnectDriveTitle,
	MChangeSUBSTDisconnectDriveQuestion,
	MChangeVHDDisconnectDriveTitle,
	MChangeVHDDisconnectDriveQuestion,

	MChangeHotPlugDisconnectDriveTitle,
	MChangeHotPlugDisconnectDriveQuestion,
	MHotPlugDisks,
	MChangeCouldNotEjectHotPlugMedia,
	MChangeCouldNotEjectHotPlugMedia2,
	MChangeHotPlugNotify1,
	MChangeHotPlugNotify2,
	MHotPlugListTitle,

	MChangeDriveDisconnectTitle,
	MChangeDriveDisconnectQuestion,
	MChangeDriveDisconnectMapped,
	MChangeDriveDisconnectReconnect,

	MChangeDriveAskDisconnect,
	MChangeWaitingLoadDisk,
	MChangeCouldNotEjectMedia,
	MChangeDriveConfigure,
	MChangeDriveShowDiskType,
	MChangeDriveShowPath,
	MChangeDriveShowLabel,
	MChangeDriveShowLabelUseShell,
	MChangeDriveShowFileSystem,
	MChangeDriveShowSize,
	MChangeDriveShowSizeFloat,
	MChangeDriveShowRemovableDrive,
	MChangeDriveShowPlugins,
	MChangeDriveSortPluginsByHotkey,
	MChangeDriveShowCD,
	MChangeDriveShowNetworkDrive,
	MChangeDriveShowVirtualDisk,

	MSearchFileTitle,
	MCannotCreateListTemp,

	MDragFiles,
	MDragMove,
	MDragCopy,

	MProcessListTitle,
	MKillProcessTitle,
	MAskKillProcess,
	MKillProcessWarning,
	MKillProcessKill,
	MCannotKillProcess,
	MCannotKillProcessPerm,

	MQuickViewTitle,
	MQuickViewUnknownReparsePoint,
	MQuickViewNoData,
	MQuickViewFolders,
	MQuickViewFiles,
	MQuickViewBytes,
	MQuickViewAllocated,
	MQuickViewCluster,
	MQuickViewSlack,
	MQuickViewMFTOverhead,

	MSetAttrTitle,
	MSetAttrFor,
	MSetAttrSelectedObjects,
	MSetAttrHardLinks,
	MSetAttrJunction,
	MSetAttrSymlink,
	MSetAttrVolMount,
	MSetAttrDfsTargets,
	MSetAttrAppExecLink,
	MSetAttrUnknownReparsePoint,
	MSetAttrReadOnly,
	MSetAttrArchive,
	MSetAttrHidden,
	MSetAttrSystem,
	MSetAttrCompressed,
	MSetAttrEncrypted,
	MSetAttrNotIndexed,
	MSetAttrSparse,
	MSetAttrTemporary,
	MSetAttrOffline,
	MSetAttrReparsePoint,
	MSetAttrVirtual,
	MSetAttrIntegrityStream,
	MSetAttrNoScrubData,
	MSetAttrPinned,
	MSetAttrUnpinned,
	MSetAttrRecallOnOpen,
	MSetAttrRecallOnDataAccess,
	MSetAttrStrictlySequential,
	MSetAttrDevice,
	MSetAttrMore,
	MSetAttrSubfolders,
	MSetAttrOwner,
	MSetAttrModification,
	MSetAttrCreation,
	MSetAttrLastAccess,
	MSetAttrChange,
	MSetAttrOriginal,
	MSetAttrCurrent,
	MSetAttrBlank,
	MSetAttrSet,

	MSetAttrDateTitleMDY,
	MSetAttrDateTitleDMY,
	MSetAttrDateTitleYMD,
	MSetAttrTimeTitle,
	MSetAttrSystemDialog,

	MSetAttrSetting,
	MSetAttrCannotFor,
	MSetAttrCompressedCannotFor,
	MSetAttrEncryptedCannotFor,
	MSetAttrSparseCannotFor,
	MSetAttrTimeCannotFor,
	MSetAttrOwnerCannotFor,
	MSetAttrReparsePointCannotFor,

	MSetColorPanel,
	MSetColorDialog,
	MSetColorWarning,
	MSetColorMenu,
	MSetColorHMenu,
	MSetColorKeyBar,
	MSetColorCommandLine,
	MSetColorClock,
	MSetColorViewer,
	MSetColorEditor,
	MSetColorHelp,
	MSetDefaultColors,
	MSetDefaultColorsRGB,

	MSetColorPanelNormal,
	MSetColorPanelSelected,
	MSetColorPanelHighlightedText,
	MSetColorPanelHighlightedInfo,
	MSetColorPanelDragging,
	MSetColorPanelBox,
	MSetColorPanelNormalCursor,
	MSetColorPanelSelectedCursor,
	MSetColorPanelNormalTitle,
	MSetColorPanelSelectedTitle,
	MSetColorPanelColumnTitle,
	MSetColorPanelTotalInfo,
	MSetColorPanelSelectedInfo,
	MSetColorPanelScrollbar,
	MSetColorPanelScreensNumber,

	MSetColorDialogNormal,
	MSetColorDialogHighlighted,
	MSetColorDialogDisabled,
	MSetColorDialogBox,
	MSetColorDialogBoxTitle,
	MSetColorDialogHighlightedBoxTitle,
	MSetColorDialogTextInput,
	MSetColorDialogUnchangedTextInput,
	MSetColorDialogSelectedTextInput,
	MSetColorDialogEditDisabled,
	MSetColorDialogButtons,
	MSetColorDialogSelectedButtons,
	MSetColorDialogHighlightedButtons,
	MSetColorDialogSelectedHighlightedButtons,
	MSetColorDialogDefaultButton,
	MSetColorDialogSelectedDefaultButton,
	MSetColorDialogHighlightedDefaultButton,
	MSetColorDialogSelectedHighlightedDefaultButton,
	MSetColorDialogListBoxControl,
	MSetColorDialogComboBoxControl,

	MSetColorDialogListText,
	MSetColorDialogListSelectedText,
	MSetColorDialogListHighLight,
	MSetColorDialogListSelectedHighLight,
	MSetColorDialogListDisabled,
	MSetColorDialogListBox,
	MSetColorDialogListTitle,
	MSetColorDialogListGrayed,
	MSetColorDialogSelectedListGrayed,
	MSetColorDialogListScrollBar,
	MSetColorDialogListArrows,
	MSetColorDialogListArrowsSelected,
	MSetColorDialogListArrowsDisabled,

	MSetColorMenuNormal,
	MSetColorMenuSelected,
	MSetColorMenuHighlighted,
	MSetColorMenuSelectedHighlighted,
	MSetColorMenuDisabled,
	MSetColorMenuGrayed,
	MSetColorMenuSelectedGrayed,
	MSetColorMenuBox,
	MSetColorMenuTitle,
	MSetColorMenuScrollBar,
	MSetColorMenuArrows,
	MSetColorMenuArrowsSelected,
	MSetColorMenuArrowsDisabled,

	MSetColorHMenuNormal,
	MSetColorHMenuSelected,
	MSetColorHMenuHighlighted,
	MSetColorHMenuSelectedHighlighted,

	MSetColorKeyBarNumbers,
	MSetColorKeyBarNames,
	MSetColorKeyBarBackground,

	MSetColorCommandLineNormal,
	MSetColorCommandLineSelected,
	MSetColorCommandLinePrefix,
	MSetColorCommandLineUserScreen,

	MSetColorClockNormal,
	MSetColorClockNormalEditor,
	MSetColorClockNormalViewer,

	MSetColorViewerNormal,
	MSetColorViewerSelected,
	MSetColorViewerStatus,
	MSetColorViewerArrows,
	MSetColorViewerScrollbar,

	MSetColorEditorNormal,
	MSetColorEditorSelected,
	MSetColorEditorStatus,
	MSetColorEditorScrollbar,

	MSetColorHelpNormal,
	MSetColorHelpHighlighted,
	MSetColorHelpReference,
	MSetColorHelpSelectedReference,
	MSetColorHelpBox,
	MSetColorHelpBoxTitle,
	MSetColorHelpScrollbar,

	MSetColorGroupsTitle,
	MSetColorItemsTitle,

	MSetColorTitle,
	MSetColorForeground,
	MSetColorBackground,
	MSetColorForegroundDefault,
	MSetColorBackgroundDefault,

	// 8 characters max
	MSetColorForeIndex,

	// 8 characters max
	MSetColorForeAARRGGBB,

	// 8 characters max
	MSetColorForeDefault,

	// 3 characters max
	MSetColorFore256,

	// 3 characters max
	MSetColorForeRGB,

	// 8 characters max
	MSetColorBackIndex,

	// 8 characters max
	MSetColorBackAARRGGBB,

	// 8 characters max
	MSetColorBackDefault,

	// 3 characters max
	MSetColorBack256,

	// 3 characters max
	MSetColorBackRGB,
	MSetColorStyle,
	MSetColorStyleInherit,
	MSetColorStyleBold,
	MSetColorStyleItalic,
	MSetColorStyleUnderline,
	MSetColorStyleUnderline2,
	MSetColorStyleOverline,
	MSetColorStyleStrikeout,
	MSetColorStyleFaint,
	MSetColorStyleBlink,
	MSetColorStyleInverse,
	MSetColorStyleInvisible,
	MSetColorSample,
	MSetColorVTHintInfo,
	MSetColorVTHintSupported,
	MSetColorVTHintNotSupported,
	MSetColorSystemDialog,
	MSetColorSet,
	MSetColorEnableVT,
	MSetColorCancel,
	MColorsPalette,
	MColorsClassicPalette,

	MSetConfirmTitle,
	MSetConfirmCopy,
	MSetConfirmMove,
	MSetConfirmRO,
	MSetConfirmDrag,
	MSetConfirmDelete,
	MSetConfirmDeleteFolders,
	MSetConfirmEsc,
	MSetConfirmRemoveConnection,
	MSetConfirmRemoveSUBST,
	MSetConfirmDetachVHD,
	MSetConfirmRemoveHotPlug,
	MSetConfirmAllowReedit,
	MSetConfirmHistoryClear,
	MSetConfirmExit,

	MPluginsManagerSettingsTitle,
	MPluginsManagerOEMPluginsSupport,
	MPluginsManagerScanSymlinks,
	MPluginsManagerOFP,
	MPluginsManagerStdAssoc,
	MPluginsManagerEvenOne,
	MPluginsManagerSFL,
	MPluginsManagerPF,
	MPluginConfirmationTitle,
	MMenuPluginStdAssociation,

	MFindFolderTitle,

	// Find folder Tree KeyBar
	MFolderTreeF1,
	MFolderTreeF2,
	MFolderTreeF3,
	MFolderTreeF4,
	MFolderTreeF5,
	MFolderTreeF6,
	MFolderTreeF7,
	MFolderTreeF8,
	MFolderTreeF9,
	MFolderTreeF10,
	MFolderTreeF11,
	MFolderTreeF12,
	MFolderTreeShiftF1,
	MFolderTreeShiftF2,
	MFolderTreeShiftF3,
	MFolderTreeShiftF4,
	MFolderTreeShiftF5,
	MFolderTreeShiftF6,
	MFolderTreeShiftF7,
	MFolderTreeShiftF8,
	MFolderTreeShiftF9,
	MFolderTreeShiftF10,
	MFolderTreeShiftF11,
	MFolderTreeShiftF12,
	MFolderTreeAltF1,
	MFolderTreeAltF2,
	MFolderTreeAltF3,
	MFolderTreeAltF4,
	MFolderTreeAltF5,
	MFolderTreeAltF6,
	MFolderTreeAltF7,
	MFolderTreeAltF8,
	MFolderTreeAltF9,
	MFolderTreeAltF10,
	MFolderTreeAltF11,
	MFolderTreeAltF12,
	MFolderTreeCtrlF1,
	MFolderTreeCtrlF2,
	MFolderTreeCtrlF3,
	MFolderTreeCtrlF4,
	MFolderTreeCtrlF5,
	MFolderTreeCtrlF6,
	MFolderTreeCtrlF7,
	MFolderTreeCtrlF8,
	MFolderTreeCtrlF9,
	MFolderTreeCtrlF10,
	MFolderTreeCtrlF11,
	MFolderTreeCtrlF12,
	MFolderTreeCtrlShiftF1,
	MFolderTreeCtrlShiftF2,
	MFolderTreeCtrlShiftF3,
	MFolderTreeCtrlShiftF4,
	MFolderTreeCtrlShiftF5,
	MFolderTreeCtrlShiftF6,
	MFolderTreeCtrlShiftF7,
	MFolderTreeCtrlShiftF8,
	MFolderTreeCtrlShiftF9,
	MFolderTreeCtrlShiftF10,
	MFolderTreeCtrlShiftF11,
	MFolderTreeCtrlShiftF12,
	MFolderTreeCtrlAltF1,
	MFolderTreeCtrlAltF2,
	MFolderTreeCtrlAltF3,
	MFolderTreeCtrlAltF4,
	MFolderTreeCtrlAltF5,
	MFolderTreeCtrlAltF6,
	MFolderTreeCtrlAltF7,
	MFolderTreeCtrlAltF8,
	MFolderTreeCtrlAltF9,
	MFolderTreeCtrlAltF10,
	MFolderTreeCtrlAltF11,
	MFolderTreeCtrlAltF12,
	MFolderTreeAltShiftF1,
	MFolderTreeAltShiftF2,
	MFolderTreeAltShiftF3,
	MFolderTreeAltShiftF4,
	MFolderTreeAltShiftF5,
	MFolderTreeAltShiftF6,
	MFolderTreeAltShiftF7,
	MFolderTreeAltShiftF8,
	MFolderTreeAltShiftF9,
	MFolderTreeAltShiftF10,
	MFolderTreeAltShiftF11,
	MFolderTreeAltShiftF12,
	MFolderTreeCtrlAltShiftF1,
	MFolderTreeCtrlAltShiftF2,
	MFolderTreeCtrlAltShiftF3,
	MFolderTreeCtrlAltShiftF4,
	MFolderTreeCtrlAltShiftF5,
	MFolderTreeCtrlAltShiftF6,
	MFolderTreeCtrlAltShiftF7,
	MFolderTreeCtrlAltShiftF8,
	MFolderTreeCtrlAltShiftF9,
	MFolderTreeCtrlAltShiftF10,
	MFolderTreeCtrlAltShiftF11,
	MFolderTreeCtrlAltShiftF12,
	MTreeTitle,
	MCannotSaveTree,
	MReadingTree,

	MUserMenuTitle,
	MChooseMenuType,
	MChooseMenuMain,
	MChooseMenuLocal,
	MMainMenuTitle,

	// <...menu (User)>
	MMainMenuUser,
	MMainMenuGlobal,
	MLocalMenuTitle,
	MAskDeleteMenuItem,
	MAskDeleteSubMenuItem,
	MUserMenuInvalidInputLabel,
	MUserMenuInvalidInputHotKey,

	MEditMenuTitle,
	MEditMenuHotKey,
	MEditMenuLabel,
	MEditMenuCommands,

	MAskInsertMenuOrCommand,
	MMenuInsertCommand,
	MMenuInsertMenu,

	MEditSubmenuTitle,
	MEditSubmenuHotKey,
	MEditSubmenuLabel,
	MEditMenuConfirmation,
	MEditMenuError,

	MViewerTitle,
	MViewerCannotOpenFile,
	// Up to 3 characters
	MViewerStatusCol,

	MViewSearchingFor,
	MViewSearchingHex,
	MViewSearchCannotFind,
	MViewSearchCannotFindHex,
	MViewSearchEod,
	MViewSearchFromBegin,
	MViewSearchBod,
	MViewSearchFromEnd,
	MViewSearchCycle,
	MViewSearchRepeat,

	MPrintTitle,
	MPrintTo,
	MPrintFilesTo,
	MPrintingFile,
	MCannotEnumeratePrinters,
	MCannotOpenPrinter,
	MCannotPrint,

	MDescribeFiles,
	MEnterDescription,

	MReadingDiz,
	MCannotUpdateDiz,

	MCfgDizTitle,
	MCfgDizListNames,
	MCfgDizSetHidden,
	MCfgDizROUpdate,
	MCfgDizStartPos,
	MCfgDizNotUpdate,
	MCfgDizUpdateIfDisplayed,
	MCfgDizAlwaysUpdate,
	MCfgDizAnsiByDefault,
	MCfgDizSaveInUTF,

	MReadingTitleFiles,
	MReadingFiles,
	MOperationNotCompleted,

	MEditPanelModes,

	MEditPanelModeName,
	MEditPanelModeTypes,
	MEditPanelModeWidths,
	MEditPanelModeStatusTypes,
	MEditPanelModeStatusWidths,
	MEditPanelModeFullscreen,
	MEditPanelModeAlignExtensions,
	MEditPanelModeAlignFolderExtensions,
	MEditPanelModeFoldersUpperCase,
	MEditPanelModeFilesLowerCase,
	MEditPanelModeUpperToLowerCase,

	MSetFolderInfoTitle,
	MSetFolderInfoNames,

	MScreensTitle,
	MScreensPanels,
	MScreensView,
	MScreensEdit,

	MAskApplyCommandTitle,
	MAskApplyCommand,

	MPluginConfigTitle,
	MPluginCommandsMenuTitle,

	MPreparingList,

	MLangTitle,
	MHelpLangTitle,

	MDefineMacroTitle,
	MDefineMacro,
	MMacroReDefinedKey,
	MMacroDeleteKey,
	MMacroCommonReDefinedKey,
	MMacroCommonDeleteKey,
	MMacroSequence,
	MMacroReDefinedKey2,
	MMacroDeleteKey2,
	MMacroEditKey,

	MMacroSettingsTitle,
	MMacroSettingsSequence,
	MMacroSettingsDescription,
	MMacroSettingsEnableOutput,
	MMacroSettingsRunAfterStart,
	MMacroSettingsActivePanel,
	MMacroSettingsPassivePanel,
	MMacroSettingsPluginPanel,
	MMacroSettingsFolders,
	MMacroSettingsSelectionPresent,
	MMacroSettingsCommandLine,
	MMacroSettingsSelectionBlockPresent,
	MMacroPluginLuamacroNotLoaded,
	MMacroRecordingIsDisabled,

	MCannotSaveFile,
	MTextSavedToTemp,

	MPluginHotKeyTitle,
	MPluginHotKey,
	MPluginInformation,
	MPluginModuleTitle,
	MPluginDescription,
	MPluginAuthor,
	MPluginVersion,
	MPluginModulePath,
	MPluginUUID,
	MPluginItemUUID,
	MPluginPrefix,
	MExceptionDialogTitle,
	MExceptionDialogMessage1,
	MExceptionDialogMessage2,
	MExceptionDialogClipboard,
	MExcTerminate,
	MExcUnload,
	MExcContinue,
	MExcFullDump,

	MNetUserName,
	MNetUserPassword,

	MReadFolderError,

	MPlgBadVers,
	MPlgRequired,
	MPlgRequired2,
	MPlgLoadPluginError,

	MHelpTitle,
	MHelpActivatorURL,
	MHelpActivatorFormat,
	MHelpActivatorQ,
	MCannotOpenHelp,
	MHelpTopicNotFound,

	MPluginsHelpTitle,
	MDocumentsHelpTitle,
	MHelpSearchCannotFind,

	// Help KeyBar F1-12
	MHelpF1,
	MHelpF2,
	MHelpF3,
	MHelpF4,
	MHelpF5,
	MHelpF6,
	MHelpF7,
	MHelpF8,
	MHelpF9,
	MHelpF10,
	MHelpF11,
	MHelpF12,

	// Help KeyBar Shift+F1-12
	MHelpShiftF1,
	MHelpShiftF2,
	MHelpShiftF3,
	MHelpShiftF4,
	MHelpShiftF5,
	MHelpShiftF6,
	MHelpShiftF7,
	MHelpShiftF8,
	MHelpShiftF9,
	MHelpShiftF10,
	MHelpShiftF11,
	MHelpShiftF12,

	// Help KeyBar Alt+F1-12
	MHelpAltF1,
	MHelpAltF2,
	MHelpAltF3,
	MHelpAltF4,
	MHelpAltF5,
	MHelpAltF6,
	MHelpAltF7,
	MHelpAltF8,
	MHelpAltF9,
	MHelpAltF10,
	MHelpAltF11,
	MHelpAltF12,

	// Help KeyBar Ctrl+F1-12
	MHelpCtrlF1,
	MHelpCtrlF2,
	MHelpCtrlF3,
	MHelpCtrlF4,
	MHelpCtrlF5,
	MHelpCtrlF6,
	MHelpCtrlF7,
	MHelpCtrlF8,
	MHelpCtrlF9,
	MHelpCtrlF10,
	MHelpCtrlF11,
	MHelpCtrlF12,

	// Help KeyBar AltShiftF1-12
	MHelpAltShiftF1,
	MHelpAltShiftF2,
	MHelpAltShiftF3,
	MHelpAltShiftF4,
	MHelpAltShiftF5,
	MHelpAltShiftF6,
	MHelpAltShiftF7,
	MHelpAltShiftF8,
	MHelpAltShiftF9,
	MHelpAltShiftF10,
	MHelpAltShiftF11,
	MHelpAltShiftF12,

	// Help KeyBar CtrlShiftF1-12
	MHelpCtrlShiftF1,
	MHelpCtrlShiftF2,
	MHelpCtrlShiftF3,
	MHelpCtrlShiftF4,
	MHelpCtrlShiftF5,
	MHelpCtrlShiftF6,
	MHelpCtrlShiftF7,
	MHelpCtrlShiftF8,
	MHelpCtrlShiftF9,
	MHelpCtrlShiftF10,
	MHelpCtrlShiftF11,
	MHelpCtrlShiftF12,

	// Help KeyBar CtrlAltF1-12
	MHelpCtrlAltF1,
	MHelpCtrlAltF2,
	MHelpCtrlAltF3,
	MHelpCtrlAltF4,
	MHelpCtrlAltF5,
	MHelpCtrlAltF6,
	MHelpCtrlAltF7,
	MHelpCtrlAltF8,
	MHelpCtrlAltF9,
	MHelpCtrlAltF10,
	MHelpCtrlAltF11,
	MHelpCtrlAltF12,

	// Help KeyBar CtrlAltShiftF1-12
	MHelpCtrlAltShiftF1,
	MHelpCtrlAltShiftF2,
	MHelpCtrlAltShiftF3,
	MHelpCtrlAltShiftF4,
	MHelpCtrlAltShiftF5,
	MHelpCtrlAltShiftF6,
	MHelpCtrlAltShiftF7,
	MHelpCtrlAltShiftF8,
	MHelpCtrlAltShiftF9,
	MHelpCtrlAltShiftF10,
	MHelpCtrlAltShiftF11,
	MHelpCtrlAltShiftF12,

	// InfoPanel KeyBar F1-F12
	MInfoF1,
	MInfoF2,
	MInfoF3,
	MInfoF4,
	MInfoF5,
	MInfoF6,
	MInfoF7,
	MInfoF8,
	MInfoF9,
	MInfoF10,
	MInfoF11,
	MInfoF12,

	// InfoPanel KeyBar Shift+F1-F12
	MInfoShiftF1,
	MInfoShiftF2,
	MInfoShiftF3,
	MInfoShiftF4,
	MInfoShiftF5,
	MInfoShiftF6,
	MInfoShiftF7,
	MInfoShiftF8,
	MInfoShiftF9,
	MInfoShiftF10,
	MInfoShiftF11,
	MInfoShiftF12,

	// InfoPanel KeyBar Alt+F1-F12
	MInfoAltF1,
	MInfoAltF2,
	MInfoAltF3,
	MInfoAltF4,
	MInfoAltF5,
	MInfoAltF6,
	MInfoAltF7,
	MInfoAltF8,
	MInfoAltF9,
	MInfoAltF10,
	MInfoAltF11,
	MInfoAltF12,

	// InfoPanel KeyBar Ctrl+F1-F12
	MInfoCtrlF1,
	MInfoCtrlF2,
	MInfoCtrlF3,
	MInfoCtrlF4,
	MInfoCtrlF5,
	MInfoCtrlF6,
	MInfoCtrlF7,
	MInfoCtrlF8,
	MInfoCtrlF9,
	MInfoCtrlF10,
	MInfoCtrlF11,
	MInfoCtrlF12,

	// InfoPanel KeyBar AltShiftF1-12
	MInfoAltShiftF1,
	MInfoAltShiftF2,
	MInfoAltShiftF3,
	MInfoAltShiftF4,
	MInfoAltShiftF5,
	MInfoAltShiftF6,
	MInfoAltShiftF7,
	MInfoAltShiftF8,
	MInfoAltShiftF9,
	MInfoAltShiftF10,
	MInfoAltShiftF11,
	MInfoAltShiftF12,

	// InfoPanel KeyBar CtrlShiftF1-12
	MInfoCtrlShiftF1,
	MInfoCtrlShiftF2,
	MInfoCtrlShiftF3,
	MInfoCtrlShiftF4,
	MInfoCtrlShiftF5,
	MInfoCtrlShiftF6,
	MInfoCtrlShiftF7,
	MInfoCtrlShiftF8,
	MInfoCtrlShiftF9,
	MInfoCtrlShiftF10,
	MInfoCtrlShiftF11,
	MInfoCtrlShiftF12,

	// InfoPanel KeyBar CtrlAltF1-12
	MInfoCtrlAltF1,
	MInfoCtrlAltF2,
	MInfoCtrlAltF3,
	MInfoCtrlAltF4,
	MInfoCtrlAltF5,
	MInfoCtrlAltF6,
	MInfoCtrlAltF7,
	MInfoCtrlAltF8,
	MInfoCtrlAltF9,
	MInfoCtrlAltF10,
	MInfoCtrlAltF11,
	MInfoCtrlAltF12,

	// InfoPanel KeyBar CtrlAltShiftF1-12
	MInfoCtrlAltShiftF1,
	MInfoCtrlAltShiftF2,
	MInfoCtrlAltShiftF3,
	MInfoCtrlAltShiftF4,
	MInfoCtrlAltShiftF5,
	MInfoCtrlAltShiftF6,
	MInfoCtrlAltShiftF7,
	MInfoCtrlAltShiftF8,
	MInfoCtrlAltShiftF9,
	MInfoCtrlAltShiftF10,
	MInfoCtrlAltShiftF11,
	MInfoCtrlAltShiftF12,

	// QView KeyBar F1-F12
	MQViewF1,
	MQViewF2,
	MQViewF3,
	MQViewF4,
	MQViewF5,
	MQViewF6,
	MQViewF7,
	MQViewF8,
	MQViewF9,
	MQViewF10,
	MQViewF11,
	MQViewF12,

	// QView KeyBar Shift+F1-F12
	MQViewShiftF1,
	MQViewShiftF2,
	MQViewShiftF3,
	MQViewShiftF4,
	MQViewShiftF5,
	MQViewShiftF6,
	MQViewShiftF7,
	MQViewShiftF8,
	MQViewShiftF9,
	MQViewShiftF10,
	MQViewShiftF11,
	MQViewShiftF12,

	// QView KeyBar Alt+F1-F12
	MQViewAltF1,
	MQViewAltF2,
	MQViewAltF3,
	MQViewAltF4,
	MQViewAltF5,
	MQViewAltF6,
	MQViewAltF7,
	MQViewAltF8,
	MQViewAltF9,
	MQViewAltF10,
	MQViewAltF11,
	MQViewAltF12,

	// QView KeyBar Ctrl+F1-F12
	MQViewCtrlF1,
	MQViewCtrlF2,
	MQViewCtrlF3,
	MQViewCtrlF4,
	MQViewCtrlF5,
	MQViewCtrlF6,
	MQViewCtrlF7,
	MQViewCtrlF8,
	MQViewCtrlF9,
	MQViewCtrlF10,
	MQViewCtrlF11,
	MQViewCtrlF12,

	// QView KeyBar AltShiftF1-12
	MQViewAltShiftF1,
	MQViewAltShiftF2,
	MQViewAltShiftF3,
	MQViewAltShiftF4,
	MQViewAltShiftF5,
	MQViewAltShiftF6,
	MQViewAltShiftF7,
	MQViewAltShiftF8,
	MQViewAltShiftF9,
	MQViewAltShiftF10,
	MQViewAltShiftF11,
	MQViewAltShiftF12,

	// QView KeyBar CtrlShiftF1-12
	MQViewCtrlShiftF1,
	MQViewCtrlShiftF2,
	MQViewCtrlShiftF3,
	MQViewCtrlShiftF4,
	MQViewCtrlShiftF5,
	MQViewCtrlShiftF6,
	MQViewCtrlShiftF7,
	MQViewCtrlShiftF8,
	MQViewCtrlShiftF9,
	MQViewCtrlShiftF10,
	MQViewCtrlShiftF11,
	MQViewCtrlShiftF12,

	// QView KeyBar CtrlAltF1-12
	MQViewCtrlAltF1,
	MQViewCtrlAltF2,
	MQViewCtrlAltF3,
	MQViewCtrlAltF4,
	MQViewCtrlAltF5,
	MQViewCtrlAltF6,
	MQViewCtrlAltF7,
	MQViewCtrlAltF8,
	MQViewCtrlAltF9,
	MQViewCtrlAltF10,
	MQViewCtrlAltF11,
	MQViewCtrlAltF12,

	// QView KeyBar CtrlAltShiftF1-12
	MQViewCtrlAltShiftF1,
	MQViewCtrlAltShiftF2,
	MQViewCtrlAltShiftF3,
	MQViewCtrlAltShiftF4,
	MQViewCtrlAltShiftF5,
	MQViewCtrlAltShiftF6,
	MQViewCtrlAltShiftF7,
	MQViewCtrlAltShiftF8,
	MQViewCtrlAltShiftF9,
	MQViewCtrlAltShiftF10,
	MQViewCtrlAltShiftF11,
	MQViewCtrlAltShiftF12,

	// Tree KeyBar F1-F12
	MKBTreeF1,
	MKBTreeF2,
	MKBTreeF3,
	MKBTreeF4,
	MKBTreeF5,
	MKBTreeF6,
	MKBTreeF7,
	MKBTreeF8,
	MKBTreeF9,
	MKBTreeF10,
	MKBTreeF11,
	MKBTreeF12,

	// Tree KeyBar Shift+F1-F12
	MKBTreeShiftF1,
	MKBTreeShiftF2,
	MKBTreeShiftF3,
	MKBTreeShiftF4,
	MKBTreeShiftF5,
	MKBTreeShiftF6,
	MKBTreeShiftF7,
	MKBTreeShiftF8,
	MKBTreeShiftF9,
	MKBTreeShiftF10,
	MKBTreeShiftF11,
	MKBTreeShiftF12,

	// Tree KeyBar Alt+F1-F12
	MKBTreeAltF1,
	MKBTreeAltF2,
	MKBTreeAltF3,
	MKBTreeAltF4,
	MKBTreeAltF5,
	MKBTreeAltF6,
	MKBTreeAltF7,
	MKBTreeAltF8,
	MKBTreeAltF9,
	MKBTreeAltF10,
	MKBTreeAltF11,
	MKBTreeAltF12,

	// Tree KeyBar Ctrl+F1-F12
	MKBTreeCtrlF1,
	MKBTreeCtrlF2,
	MKBTreeCtrlF3,
	MKBTreeCtrlF4,
	MKBTreeCtrlF5,
	MKBTreeCtrlF6,
	MKBTreeCtrlF7,
	MKBTreeCtrlF8,
	MKBTreeCtrlF9,
	MKBTreeCtrlF10,
	MKBTreeCtrlF11,
	MKBTreeCtrlF12,

	// Tree KeyBar AltShiftF1-12
	MKBTreeAltShiftF1,
	MKBTreeAltShiftF2,
	MKBTreeAltShiftF3,
	MKBTreeAltShiftF4,
	MKBTreeAltShiftF5,
	MKBTreeAltShiftF6,
	MKBTreeAltShiftF7,
	MKBTreeAltShiftF8,
	MKBTreeAltShiftF9,
	MKBTreeAltShiftF10,
	MKBTreeAltShiftF11,
	MKBTreeAltShiftF12,

	// Tree KeyBar CtrlShiftF1-12
	MKBTreeCtrlShiftF1,
	MKBTreeCtrlShiftF2,
	MKBTreeCtrlShiftF3,
	MKBTreeCtrlShiftF4,
	MKBTreeCtrlShiftF5,
	MKBTreeCtrlShiftF6,
	MKBTreeCtrlShiftF7,
	MKBTreeCtrlShiftF8,
	MKBTreeCtrlShiftF9,
	MKBTreeCtrlShiftF10,
	MKBTreeCtrlShiftF11,
	MKBTreeCtrlShiftF12,

	// Tree KeyBar CtrlAltF1-12
	MKBTreeCtrlAltF1,
	MKBTreeCtrlAltF2,
	MKBTreeCtrlAltF3,
	MKBTreeCtrlAltF4,
	MKBTreeCtrlAltF5,
	MKBTreeCtrlAltF6,
	MKBTreeCtrlAltF7,
	MKBTreeCtrlAltF8,
	MKBTreeCtrlAltF9,
	MKBTreeCtrlAltF10,
	MKBTreeCtrlAltF11,
	MKBTreeCtrlAltF12,

	// Tree KeyBar CtrlAltShiftF1-12
	MKBTreeCtrlAltShiftF1,
	MKBTreeCtrlAltShiftF2,
	MKBTreeCtrlAltShiftF3,
	MKBTreeCtrlAltShiftF4,
	MKBTreeCtrlAltShiftF5,
	MKBTreeCtrlAltShiftF6,
	MKBTreeCtrlAltShiftF7,
	MKBTreeCtrlAltShiftF8,
	MKBTreeCtrlAltShiftF9,
	MKBTreeCtrlAltShiftF10,
	MKBTreeCtrlAltShiftF11,
	MKBTreeCtrlAltShiftF12,

	MCopyTimeInfoElapsed,
	MCopyTimeInfoRemaining,
	// Bytes per second
	MCopyTimeInfoSpeed,

	MKeyESCWasPressed,
	MDoYouWantToCancel,
	MDoYouWantToContinue,

	MCheckingFileInPlugin,

	MDialogType,
	MHelpType,
	MFolderTreeType,
	MVMenuType,

	MIncorrectMask,

	MPanelBracketsForLongName,

	MComspecNotFound,

	MFileFilterTitle,
	MFileHilightTitle,
	MFileFilterName,
	MFileFilterMatchMask,
	MFileFilterSize,
	// up to 4 characters
	MFileFilterSizeFromSign,
	// up to 4 characters
	MFileFilterSizeToSign,
	MFileHardLinksCount,
	MFileFilterDate,
	MFileFilterWrited,
	MFileFilterCreated,
	MFileFilterOpened,
	MFileFilterChanged,
	MFileFilterDateRelative,
	// up to 4 characters
	MFileFilterDateAfterSign,
	// up to 4 characters
	MFileFilterDateBeforeSign,
	MFileFilterCurrent,
	MFileFilterBlank,
	MFileFilterAttr,
	MFileFilterAttrChoose,
	MFileFilterAttrReadOnly,
	MFileFilterAttrArcive,
	MFileFilterAttrHidden,
	MFileFilterAttrSystem,
	MFileFilterAttrCompressed,
	MFileFilterAttrEncrypted,
	MFileFilterAttrDirectory,
	MFileFilterAttrNotIndexed,
	MFileFilterAttrSparse,
	MFileFilterAttrTemporary,
	MFileFilterAttrReparse,
	MFileFilterAttrOffline,
	MFileFilterAttrVirtual,
	MFileFilterAttrIntegrityStream,
	MFileFilterAttrNoScrubData,
	MFileFilterAttrPinned,
	MFileFilterAttrUnpinned,
	MFileFilterAttrRecallOnOpen,
	MFileFilterAttrRecallOnDataAccess,
	MFileFilterAttrStrictlySequential,
	MFileFilterReset,
	MFileFilterMakeTransparent,
	MFileFilterCancel,
	MBadFileSizeFormat,

	MFarTitleAddonsAdmin,
	MElevationRequired,
	MElevationRequiredPrivileges,
	MElevationRequiredProcess,
	MElevationRequiredDelete,
	MElevationRequiredCopy,
	MElevationRequiredMove,
	MElevationRequiredReplace,
	MElevationRequiredGetAttributes,
	MElevationRequiredSetAttributes,
	MElevationRequiredHardLink,
	MElevationRequiredSymLink,
	MElevationRequiredRecycle,
	MElevationRequiredList,
	MElevationRequiredSetOwner,
	MElevationRequiredOpen,
	MElevationRequiredEncryptFile,
	MElevationRequiredDecryptFile,
	MElevationDoForAll,
	MElevationDoNotAskAgainInTheCurrentSession,
	MCompletionHistoryTitle,
	MCompletionEnvironmentTitle,
	MCompletionFilesTitle,
	MObjectLockedReason,
	MObjectLockedReasonPlayed,
	MObjectLockedReasonEdited,
	MObjectLockedReasonOpened,
	MObjectLockedAndMore,
	MObjectLockedSwitchTo,
	MObjectLockedClose,
	MObjectLockedReasonSessionMismatch,
	MObjectLockedReasonCriticalProcess,
	MObjectLockedReasonCriticalService,
	MObjectLockedReasonDetectedSelf,
	MProblemDb,
	MShowConfigFolders,
	MBadLanguageFile,
	MLanguageStringNotFound,
	MCharacterIsNotSupportedByTheCodepage,
	// keys
	MKeyLaunchMediaSelect,
	MKeyBrowserFavorites,
	MKeyMediaPrevTrack,
	MKeyMediaPlayPause,
	MKeyMediaNextTrack,
	MKeyBrowserRefresh,
	MKeyBrowserForward,
	MKeyBrowserSearch,
	MKeyMswheelRight,
	MKeyMswheelDown,
	MKeyMswheelLeft,
	MKeyBrowserStop,
	MKeyBrowserHome,
	MKeyBrowserBack,
	MKeyVolumeMute,
	MKeyVolumeDown,
	MKeyScrolllock,
	MKeyLaunchMail,
	MKeyLaunchApp2,
	MKeyLaunchApp1,
	MKeyMswheelUp,
	MKeyMediaStop,
	MKeyBackslash,
	MKeyMsm1click,
	MKeyMsm2click,
	MKeyMsm3click,
	MKeyMslclick,
	MKeyMsrclick,
	MKeyVolumeUp,
	MKeySubtract,
	MKeyNumenter,
	MKeyMultiply,
	MKeyCapslock,
	MKeyPrntscrn,
	MKeyNumlock,
	MKeyDecimal,
	MKeyStandby,
	MKeyDivide,
	MKeyNumdel,
	MKeySpace,
	MKeyRight,
	MKeyPause,
	MKeyEnter,
	MKeyClear,
	MKeyBreak,
	MKeyPgup,
	MKeyPgdn,
	MKeyLeft,
	MKeyHome,
	MKeyDown,
	MKeyApps,
	MKeyRwin,
	MKeyNumpad9,
	MKeyNumpad8,
	MKeyNumpad7,
	MKeyNumpad6,
	MKeyNumpad5,
	MKeyNumpad4,
	MKeyNumpad3,
	MKeyNumpad2,
	MKeyNumpad1,
	MKeyNumpad0,
	MKeyLwin,
	MKeyTab,
	MKeyIns,
	MKeyF10,
	MKeyF11,
	MKeyF12,
	MKeyF13,
	MKeyF14,
	MKeyF15,
	MKeyF16,
	MKeyF17,
	MKeyF18,
	MKeyF19,
	MKeyF20,
	MKeyF21,
	MKeyF22,
	MKeyF23,
	MKeyF24,
	MKeyEsc,
	MKeyEnd,
	MKeyDel,
	MKeyAdd,
	MKeyUp,
	MKeyF9,
	MKeyF8,
	MKeyF7,
	MKeyF6,
	MKeyF5,
	MKeyF4,
	MKeyF3,
	MKeyF2,
	MKeyF1,
	MKeyBs,
	MKeyBackbracket,
	MKeyQuote,
	MKeyBracket,
	MKeyColon,
	MKeySemicolon,
	MKeySlash,
	MKeyDot,
	MKeyComma,
	MKeyRCtrl,
	MKeyShift,
	MKeyCtrl,
	MKeyRAlt,
	// keys end
	MKeyAlt,

	MNewFileName,
};

template<class T>
constexpr lng operator+(lng Id, T Shift)
{
	return static_cast<lng>(std::to_underlying(Id) + Shift);
}

inline lng operator++(lng& Id, int)
{
	const auto Value = Id;
	Id = Id + 1;
	return Value;
}

const string& msg(lng Id);

#endif // LANG_HPP_BB6D2D7F_CD59_4D0F_B11D_2077A8A22947
